"""Check test coverage against configurable thresholds.

Validates that code coverage meets the required threshold by parsing Cobertura
XML reports (generated by ``pytest-cov``). Supports per-module thresholds via
a ``coverage.toml`` config file.

Usage::

    hephaestus-check-coverage --path src/ --coverage-file coverage.xml
    hephaestus-check-coverage --threshold 80 --path mypackage/
    hephaestus-check-coverage --config coverage.toml --verbose
    hephaestus-check-coverage --check-omit-justification
"""

from __future__ import annotations

import argparse
import ast
import logging
import sys
from pathlib import Path
from typing import Any, cast

from hephaestus.cli.utils import create_validation_parser, emit_json_status, format_output
from hephaestus.io.toml import import_tomllib
from hephaestus.utils.helpers import get_repo_root

logger = logging.getLogger(__name__)

tomllib = import_tomllib()

_AUTOMATION_PKG = "hephaestus.automation"
_MODULE_PREFIX = "hephaestus/automation/"
_PACKAGE_GLOB_SUFFIXES = ("/*.py", "/*")
_UNIT_TEST_DIR = "tests/unit/automation"


def load_coverage_config(config_file: Path | None = None) -> dict[str, Any]:
    """Load coverage configuration from ``coverage.toml``.

    Args:
        config_file: Path to ``coverage.toml``. If None, looks for
            ``coverage.toml`` in the repo root.

    Returns:
        Dictionary with coverage configuration. Returns defaults if
        file not found.

    """
    if config_file is None:
        try:
            repo_root = get_repo_root()
            config_file = repo_root / "coverage.toml"
        except (FileNotFoundError, RuntimeError):
            return _default_config()

    if not config_file.exists():
        return _default_config()

    if tomllib is None:
        logger.warning("tomllib/tomli not available, using default coverage config")
        return _default_config()

    try:
        with open(config_file, "rb") as f:
            config = tomllib.load(f)
        return cast(dict[Any, Any], config)
    except Exception as e:
        logger.warning("Failed to load config from %s: %s", config_file, e)
        return _default_config()


def _default_config() -> dict[str, Any]:
    """Return the default coverage configuration."""
    return {"coverage": {"target": 90.0, "minimum": 80.0}}


def _coverage_omit_entries(repo_root: Path) -> list[str]:
    """Return string coverage omit entries from ``pyproject.toml``."""
    if tomllib is None:
        raise RuntimeError("tomllib/tomli not available; cannot parse pyproject.toml")

    with open(repo_root / "pyproject.toml", "rb") as f:
        pyproject = tomllib.load(f)
    omit = pyproject.get("tool", {}).get("coverage", {}).get("run", {}).get("omit", [])
    return sorted(entry for entry in omit if isinstance(entry, str))


def _automation_module_from_omit_entry(entry: str) -> str | None:
    """Return the short automation module name represented by an omit entry."""
    if not entry.startswith(_MODULE_PREFIX):
        return None
    relative_entry = entry[len(_MODULE_PREFIX) :]
    if relative_entry.endswith(".py") and "/" not in relative_entry:
        return relative_entry[: -len(".py")]
    for suffix in _PACKAGE_GLOB_SUFFIXES:
        if relative_entry.endswith(suffix):
            return relative_entry[: -len(suffix)].split("/", 1)[0]
    return None


def _automation_omit_entries(repo_root: Path) -> list[tuple[str, str]]:
    """Return ``(module, entry)`` pairs for automation coverage omits."""
    return sorted(
        (module, entry)
        for entry in _coverage_omit_entries(repo_root)
        if (module := _automation_module_from_omit_entry(entry)) is not None
    )


def _omitted_automation_modules(repo_root: Path) -> list[str]:
    """Return short automation module names from ``pyproject.toml`` coverage omits."""
    modules: set[str] = set()
    for module, _entry in _automation_omit_entries(repo_root):
        modules.add(module)
    return sorted(modules)


def _imported_automation_modules(source: str) -> set[str]:
    """Return short names of ``hephaestus.automation`` modules imported by ``source``."""
    found: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom):
            module = node.module or ""
            if module == _AUTOMATION_PKG:
                found.update(alias.name for alias in node.names)
            elif module.startswith(_AUTOMATION_PKG + "."):
                found.add(module[len(_AUTOMATION_PKG) + 1 :].split(".")[0])
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith(_AUTOMATION_PKG + "."):
                    found.add(alias.name[len(_AUTOMATION_PKG) + 1 :].split(".")[0])
    return found


def _defines_a_test(source: str) -> bool:
    """Return True when ``source`` defines at least one pytest-style test function."""
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith(
            "test_"
        ):
            return True
        if (
            isinstance(node, ast.ClassDef)
            and node.name.startswith("Test")
            and any(
                isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef))
                and child.name.startswith("test_")
                for child in node.body
            )
        ):
            return True
    return False


def _backing_test_sources(repo_root: Path) -> dict[Path, str]:
    """Return source text for automation unit tests that can justify coverage omits."""
    test_root = repo_root / _UNIT_TEST_DIR
    return {
        path: path.read_text(encoding="utf-8")
        for path in sorted(test_root.rglob("test_*.py"))
        if path.is_file()
    }


def find_unjustified_coverage_omits(repo_root: Path) -> list[str]:
    """Return coverage-omitted automation modules without backing unit tests.

    The guard enforces the issue #1422 proxy invariant: every automation module
    represented in ``[tool.coverage.run].omit`` must be imported by at least one
    ``tests/unit/automation/test_*.py`` file that defines a ``test_*`` function.
    It does not claim every pure helper is asserted; it blocks silent omit-list
    growth without a test suite anchor.

    Args:
        repo_root: Repository root containing ``pyproject.toml``.

    Returns:
        Sorted short module names that lack a backing unit-test suite.

    """
    omitted_modules = _omitted_automation_modules(repo_root)
    sources = _backing_test_sources(repo_root)
    return sorted(
        module
        for module in omitted_modules
        if not any(
            module in _imported_automation_modules(source) and _defines_a_test(source)
            for source in sources.values()
        )
    )


def find_stale_coverage_omits(repo_root: Path) -> list[str]:
    """Return coverage-omitted automation modules missing from the source tree.

    Args:
        repo_root: Repository root containing ``pyproject.toml`` and
            ``hephaestus/automation``.

    Returns:
        Sorted short module names whose omit-list entry no longer matches
        source files under ``hephaestus/automation``.

    """
    automation_root = repo_root / _MODULE_PREFIX
    return sorted(
        module
        for module, entry in _automation_omit_entries(repo_root)
        if not any(automation_root.glob(entry[len(_MODULE_PREFIX) :]))
    )


def get_module_threshold(path: str, config: dict[str, Any]) -> float:
    """Get coverage threshold for a specific module.

    Tries an exact path match first, then prefix match, then falls back
    to the overall minimum threshold.

    Args:
        path: Module path (e.g. ``"mypackage/core"``).
        config: Configuration dictionary from :func:`load_coverage_config`.

    Returns:
        Minimum coverage threshold for the module.

    """
    modules = config.get("coverage", {}).get("modules", {})

    if path in modules:
        return cast(float, modules[path].get("minimum", 90.0))

    for module_path in sorted(modules.keys(), key=len, reverse=True):
        if path.startswith(module_path):
            return cast(float, modules[module_path].get("minimum", 90.0))

    return cast(float, config.get("coverage", {}).get("minimum", 80.0))


def parse_coverage_report(coverage_file: Path) -> float | None:
    """Parse a Cobertura XML coverage report and extract total coverage.

    Args:
        coverage_file: Path to ``coverage.xml`` file.

    Returns:
        Coverage percentage (0-100), or None if file not found or invalid.

    """
    if not coverage_file.exists():
        logger.error("Coverage file not found: %s", coverage_file)
        return None

    try:
        import defusedxml.ElementTree as ElementTree
    except ImportError:
        logger.warning(
            "defusedxml not installed. "
            "Install with: pip install HomericIntelligence-Hephaestus[xml]"
        )
        return None

    try:
        tree = ElementTree.parse(str(coverage_file))
        root = tree.getroot()
        line_rate = root.get("line-rate")
        if line_rate is not None:
            return float(line_rate) * 100.0
        logger.warning("No line-rate found in %s", coverage_file)
        return None
    except Exception as e:
        logger.error("Error parsing coverage file: %s", e)
        return None


def parse_module_coverage(coverage_file: Path) -> dict[str, tuple[float, float]]:
    """Parse per-module coverage from Cobertura XML report.

    Extracts line-rate and branch-rate for each <class> element
    (representing a module/file).

    Args:
        coverage_file: Path to ``coverage.xml`` file.

    Returns:
        Dictionary mapping filename to (line_rate, branch_rate) tuple, both
        as percentages (0-100).

    Raises:
        FileNotFoundError: If coverage file does not exist.
        RuntimeError: If defusedxml is not available or parsing fails.

    """
    if not coverage_file.exists():
        raise FileNotFoundError(f"Coverage file not found: {coverage_file}")

    try:
        import defusedxml.ElementTree as ElementTree
    except ImportError as err:
        raise RuntimeError(
            "defusedxml not installed. "
            "Install with: pip install HomericIntelligence-Hephaestus[xml]"
        ) from err

    try:
        tree = ElementTree.parse(str(coverage_file))
        root = tree.getroot()
    except Exception as e:
        raise RuntimeError(f"Error parsing coverage file: {e}") from e

    modules: dict[str, tuple[float, float]] = {}
    for class_elem in root.findall(".//class"):
        filename = class_elem.get("filename")
        if filename is None:
            continue
        line_rate_str = class_elem.get("line-rate")
        branch_rate_str = class_elem.get("branch-rate")
        try:
            line_rate = float(line_rate_str or "0") * 100.0 if line_rate_str else 0.0
            branch_rate = float(branch_rate_str or "0") * 100.0 if branch_rate_str else 0.0
            modules[filename] = (line_rate, branch_rate)
        except (ValueError, TypeError) as e:
            logger.warning("Could not parse rates for %s: %s", filename, e)
            continue

    return modules


def check_coverage(threshold: float, path: str, coverage_file: Path) -> bool:
    """Check if coverage meets threshold.

    Args:
        threshold: Minimum required coverage percentage.
        path: Path to source code being tested (for display).
        coverage_file: Path to coverage report.

    Returns:
        True if coverage meets threshold or coverage is not available,
        False only if coverage parsing succeeds but is below threshold.

    """
    coverage = parse_coverage_report(coverage_file)

    if coverage is None:
        # User-facing CLI report output — intentionally written to stdout.
        print(f"\nCoverage Report: {path}")
        print("  Status: Coverage data not available")
        print("  PASSED - Coverage check skipped")
        return True

    # User-facing CLI report output — intentionally written to stdout.
    print(f"\nCoverage Report: {path}")
    print(f"  Coverage: {coverage:.2f}%")
    print(f"  Threshold: {threshold:.2f}%")

    if coverage >= threshold:
        print("  PASSED - Coverage meets threshold")
        return True

    gap = threshold - coverage
    print(f"  FAILED - Coverage is {gap:.2f}% below threshold")
    return False


def _check_module_floors(
    args: argparse.Namespace,
    config: dict[str, Any],
    modules_config: dict[str, Any],
) -> int:
    """Check per-module coverage floors from the parsed config.

    Args:
        args: Parsed CLI arguments (coverage_file, json, verbose).
        config: Full coverage configuration dictionary.
        modules_config: The ``[coverage.modules]`` sub-dict.

    Returns:
        0 if all configured modules meet their floor, 1 otherwise.

    """
    try:
        module_coverage = parse_module_coverage(args.coverage_file)
    except (FileNotFoundError, RuntimeError) as e:
        if args.json:
            emit_json_status(1, message=f"Could not parse module coverage: {e}")
        else:
            print(f"\nERROR: Could not parse module coverage: {e}", file=sys.stderr)
        return 1

    all_modules_pass = True
    for module_path in modules_config:
        module_threshold = get_module_threshold(module_path, config)
        if module_path not in module_coverage:
            # Module is configured but not found in the coverage report — fail loudly
            if not args.json:
                print(
                    f"\nERROR: Module {module_path} expected in coverage report but not found",
                    file=sys.stderr,
                )
            all_modules_pass = False
            continue

        line_rate, branch_rate = module_coverage[module_path]
        # Use branch rate for comparison if available, otherwise line rate
        coverage_metric = branch_rate if branch_rate > 0 else line_rate
        if coverage_metric < module_threshold:
            if not args.json:
                print(
                    f"\nModule {module_path}: {coverage_metric:.2f}% "
                    f"(below threshold of {module_threshold:.2f}%)",
                    file=sys.stderr,
                )
            all_modules_pass = False
        elif not args.json and args.verbose:
            print(f"  {module_path}: {coverage_metric:.2f}% ✓")

    return 0 if all_modules_pass else 1


def _emit_json_report(args: argparse.Namespace, threshold: float) -> int:
    """Emit a JSON coverage report and return an exit code.

    Args:
        args: Parsed CLI arguments (coverage_file, path).
        threshold: Effective coverage threshold to test against.

    Returns:
        0 if coverage passes (or data unavailable), 1 if below threshold.

    """
    coverage_value = parse_coverage_report(args.coverage_file)
    if coverage_value is None:
        report: dict[str, Any] = {
            "path": args.path,
            "threshold": threshold,
            "coverage": None,
            "passed": True,
            "message": "Coverage data not available; check skipped",
        }
        print(format_output(report, "json"))
        return 0
    passed = coverage_value >= threshold
    report = {
        "path": args.path,
        "threshold": threshold,
        "coverage": coverage_value,
        "passed": passed,
    }
    print(format_output(report, "json"))
    return 0 if passed else 1


def _check_omit_justification_cli(repo_root: Path, *, json_output: bool) -> int:
    """Run the coverage omit-list justification guard for the CLI."""
    missing = find_stale_coverage_omits(repo_root)
    unjustified = find_unjustified_coverage_omits(repo_root)
    if missing or unjustified:
        messages = []
        if missing:
            messages.append(
                "coverage omit entries point at missing automation modules: " + ", ".join(missing)
            )
        if unjustified:
            messages.append(
                "coverage-omitted automation modules lack backing unit tests: "
                + ", ".join(unjustified)
            )
        message = "; ".join(messages)
        if json_output:
            emit_json_status(
                1,
                message=message,
                missing_modules=missing,
                unjustified_modules=unjustified,
            )
        else:
            print("ERROR: Coverage omit-list justification failed.", file=sys.stderr)
            if missing:
                print(
                    "The following omit entries no longer match source files "
                    "under hephaestus/automation:",
                    file=sys.stderr,
                )
                for module in missing:
                    print(f"  - {module}", file=sys.stderr)
            if unjustified:
                print(
                    "The following hephaestus/automation modules are omitted from "
                    "coverage but have no backing tests/unit/automation/test_*.py suite:",
                    file=sys.stderr,
                )
                for module in unjustified:
                    print(f"  - {module}", file=sys.stderr)
            print(
                "Add focused unit tests for each module's pure helpers, restore the "
                "missing module, or remove the module from [tool.coverage.run].omit.",
                file=sys.stderr,
            )
        return 1

    if json_output:
        emit_json_status(0, message="coverage omit-list justifications are present")
    else:
        print("Coverage omit-list justification OK.")
    return 0


def main() -> int:
    """CLI entry point for coverage checking.

    Returns:
        Exit code (0 if coverage meets threshold, 1 otherwise).

    """
    parser = create_validation_parser(
        "Check test coverage against threshold",
        include_repo_root=True,
        epilog="Example: %(prog)s --threshold 80 --path mypackage/",
    )
    parser.add_argument(
        "--check-omit-justification",
        action="store_true",
        help=(
            "Verify every coverage-omitted hephaestus/automation module has a "
            "backing tests/unit/automation unit-test suite"
        ),
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help="Minimum required coverage percentage (overrides config)",
    )
    parser.add_argument(
        "--path",
        type=str,
        default=".",
        help="Path to source code being tested (default: .)",
    )
    parser.add_argument(
        "--coverage-file",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage report file (default: coverage.xml)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Path to coverage.toml config file",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose output",
    )

    args = parser.parse_args()

    if args.check_omit_justification:
        repo_root = args.repo_root or get_repo_root()
        return _check_omit_justification_cli(repo_root, json_output=args.json)

    config = load_coverage_config(args.config)

    if args.threshold is not None:
        threshold = args.threshold
    else:
        threshold = get_module_threshold(args.path, config)

    if args.verbose and not args.json:
        # User-facing CLI verbose output — intentionally written to stdout.
        print("Checking coverage with settings:")
        print(f"  Threshold: {threshold}%")
        print(f"  Path: {args.path}")
        print(f"  Coverage file: {args.coverage_file}")

    if not args.coverage_file.exists():
        if args.json:
            emit_json_status(1, message=f"Coverage file not found: {args.coverage_file}")
            return 1
        # User-facing actionable guidance — intentionally written to stderr so
        # the message appears even when stdout is redirected to a file.
        print(f"\nWARNING: Coverage file not found: {args.coverage_file}", file=sys.stderr)
        print(
            "\nRun tests with coverage first: pytest --cov=<package> --cov-report=xml",
            file=sys.stderr,
        )
        return 1

    # Check per-module floors if configured
    modules_config = config.get("coverage", {}).get("modules", {})
    if modules_config:
        rc = _check_module_floors(args, config, modules_config)
        if rc != 0:
            return rc

    if args.json:
        return _emit_json_report(args, threshold)

    success = check_coverage(threshold, args.path, args.coverage_file)
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
